name: scania-auth-dev

services:
  postgres:
    image: postgres:16-alpine
    container_name: scania-auth-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scania_auth
    ports:
      - "5432:5432"
    volumes:
      - scania_auth_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  scania_auth_pgdata:
